version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 5000:5000
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://user:password@db/postgres

    depends_on: 
      - db
    
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    ports:
      - 5432:5432